---
- name: Including OS-specific tasks...
  ansible.builtin.include_tasks: main-{{ ansible_distribution | lower }}.yml

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present
    gid: 1750

- name: Add Users to Docker group
  ansible.builtin.user:
    name: '{{ item }}'
    groups:
      - docker
    append: true
  loop: '{{ users }}'

- name: Enable Docker Service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
