---
- name: Retrieve Ansible Key
  onepassword.connect.field_info:
    item: 'Docker Hub'
    field: username
    vault: Ansible
  no_log: true
  register: dockerhub_username

- name: Retrieve Ansible Key
  onepassword.connect.field_info:
    item: 'Docker Hub'
    field: pat
    vault: Ansible
  no_log: true
  register: dockerhub_pat
